CRITICAL - 2024-06-30 04:40:24 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php on line 1875
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
')
 2 SYSTEMPATH\BaseModel.php(806): CodeIgniter\BaseModel->transformDataToArray('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', 'insert')
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', false)
 4 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', false)
 5 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:40:44 --> TypeError: CodeIgniter\BaseModel::timeToString(): Argument #1 ($properties) must be of type array, string given, called in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php on line 1875
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\BaseModel.php on line 1762.
 1 SYSTEMPATH\BaseModel.php(1875): CodeIgniter\BaseModel->timeToString('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
')
 2 SYSTEMPATH\BaseModel.php(806): CodeIgniter\BaseModel->transformDataToArray('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', 'insert')
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', false)
 4 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
', false)
 5 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save('{
		"Nombre": "Juan Jose",
		"Apellido1": "Valdez",
		"Apellido2": "Medina",
		"Telefono": "6688857010",
		"Email": "juanjose@gmail.com",
		"Estatus": "1"
}
')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
ERROR - 2024-06-30 04:42:29 --> mysqli_sql_exception: Unknown column 'Apellido2' in 'field list' in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tb...', 0)
#1 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\app\Controllers\Api\ClienteController.php(32): CodeIgniter\Model->insert(Array)
#8 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
#9 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
#10 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\rewrite.php(44): require_once('D:\\GitHub\\Prueb...')
#15 {main}
CRITICAL - 2024-06-30 04:42:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:42:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:42:29\', \'2024-06-30 04:42:29\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:42:29\', \'2024-06-30 04:42:29\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:42:29 --> [Caused by] mysqli_sql_exception: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:42:29\', \'2024-06-30 04:42:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:42:29\', \'2024-06-30 04:42:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:42:29\', \'2024-06-30 04:42:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:43:54 --> Error: Class name must be a valid object or a string
[Method: POST, Route: api/clientes/crear]
in APPPATH\Controllers\Api\ClienteController.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:44:24 --> Error: Class name must be a valid object or a string
[Method: POST, Route: api/clientes/crear]
in APPPATH\Controllers\Api\ClienteController.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:44:41 --> Error: Class name must be a valid object or a string
[Method: POST, Route: api/clientes/crear]
in APPPATH\Controllers\Api\ClienteController.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:44:45 --> Error: Class name must be a valid object or a string
[Method: POST, Route: api/clientes/crear]
in APPPATH\Controllers\Api\ClienteController.php on line 32.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
ERROR - 2024-06-30 04:46:40 --> mysqli_sql_exception: Unknown column 'Apellido2' in 'field list' in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tb...', 0)
#1 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\app\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save(Array)
#9 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
#10 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
#11 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\rewrite.php(44): require_once('D:\\GitHub\\Prueb...')
#16 {main}
CRITICAL - 2024-06-30 04:46:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:46:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:46:40\', \'2024-06-30 04:46:40\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:46:40\', \'2024-06-30 04:46:40\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:46:40 --> [Caused by] mysqli_sql_exception: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:46:40\', \'2024-06-30 04:46:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:46:40\', \'2024-06-30 04:46:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:46:40\', \'2024-06-30 04:46:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Api\ClienteController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
ERROR - 2024-06-30 04:59:08 --> mysqli_sql_exception: Unknown column 'Apellido2' in 'field list' in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tb...', 0)
#1 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\app\Controllers\Api\ClienteController.php(31): CodeIgniter\Model->insert(Array)
#8 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
#9 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
#10 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\rewrite.php(44): require_once('D:\\GitHub\\Prueb...')
#15 {main}
CRITICAL - 2024-06-30 04:59:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Api\ClienteController.php(31): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:59:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:59:08\', \'2024-06-30 04:59:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:59:08\', \'2024-06-30 04:59:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Api\ClienteController.php(31): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 04:59:08 --> [Caused by] mysqli_sql_exception: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:59:08\', \'2024-06-30 04:59:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:59:08\', \'2024-06-30 04:59:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 04:59:08\', \'2024-06-30 04:59:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Api\ClienteController.php(31): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 05:05:00 --> TypeError: json_decode(): Argument #1 ($json) must be of type string, stdClass given
[Method: POST, Route: api/clientes/crear]
in APPPATH\Controllers\Api\ClienteController.php on line 31.
 1 APPPATH\Controllers\Api\ClienteController.php(31): json_decode(Object(stdClass), true)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
ERROR - 2024-06-30 05:09:20 --> mysqli_sql_exception: Unknown column 'Apellido2' in 'field list' in D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tb...', 0)
#1 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\BaseModel.php(751): CodeIgniter\Model->insert(Object(stdClass), false)
#8 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\app\Controllers\Api\ClienteController.php(28): CodeIgniter\BaseModel->save(Object(stdClass))
#9 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
#10 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
#11 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\GitHub\Prueba-Tecnica-Digiosoft\workOrdersAPI\system\rewrite.php(44): require_once('D:\\GitHub\\Prueb...')
#16 {main}
CRITICAL - 2024-06-30 05:09:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
[Method: POST, Route: api/clientes/crear]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert(Object(stdClass), false)
 6 APPPATH\Controllers\Api\ClienteController.php(28): CodeIgniter\BaseModel->save(Object(stdClass))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 05:09:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 05:09:20\', \'2024-06-30 05:09:20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 05:09:20\', \'2024-06-30 05:09:20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert(Object(stdClass), false)
 8 APPPATH\Controllers\Api\ClienteController.php(28): CodeIgniter\BaseModel->save(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
CRITICAL - 2024-06-30 05:09:20 --> [Caused by] mysqli_sql_exception: Unknown column 'Apellido2' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 05:09:20\', \'2024-06-30 05:09:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 05:09:20\', \'2024-06-30 05:09:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (\'Juan Jose\', \'Valdez\', \'Medina\', \'6688857010\', \'juanjose@gmail.com\', \'1\', \'2024-06-30 05:09:20\', \'2024-06-30 05:09:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_cliente` (`Nombre`, `Apellido1`, `Apellido2`, `Telefono`, `Email`, `Estatus`, `CreatedAt`, `UpdatedAt`) VALUES (:Nombre:, :Apellido1:, :Apellido2:, :Telefono:, :Email:, :Estatus:, :CreatedAt:, :UpdatedAt:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert(Object(stdClass), false)
 9 APPPATH\Controllers\Api\ClienteController.php(28): CodeIgniter\BaseModel->save(Object(stdClass))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Api\ClienteController->create()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\ClienteController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\GitHub\\Prueba-Tecnica-Digiosoft\\workOrdersAPI\\public\\index.php')
